spring.application.name=backend

cognodb.uri=bolt+s://db-c1bfee3f.bravo.databases.cognodb.com
cognodb.username=cognodb
cognodb.password=${COGNODB_PASSWORD}f5caa14d6dd4749656520f5e40474553


server.port=8081